services:
  php:
    build:
      context: php
      dockerfile: Dockerfile
    container_name: ${PROJECT_NAME}_laravel
    working_dir: /var/www/html
    volumes:
      - ../:/var/www/html
    user: "${MY_UID}:${GID}"
    depends_on:
      - mysql
    environment:
      - UID=${MY_UID}
      - GID=${GID}
    networks:
      - network_app
    command: >
      sh -c "
        if [ ! -f artisan ]; then
          composer create-project --no-interaction laravel/laravel laravel-temp && \
          cp -r laravel-temp/* ./ && \
          cp -r laravel-temp/.* ./ 2>/dev/null || true && \
          composer config name ${COMPOSER_PROJECT_NAME} && \
          composer config type ${COMPOSER_TYPE} && \
          rm -rf laravel-temp;
        fi
        composer install
        php-fpm
      "     
  nginx:
    image: nginx:latest
    container_name: ${PROJECT_NAME}_nginx
    ports:
      - 8000:80
    volumes:
      - ../:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - network_app  
  mysql:
    image: mysql:8.0
    container_name: ${PROJECT_NAME}_database
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - network_app
volumes:
  mysql_data:
networks:
  network_app:
    name: ${PROJECT_NAME}_network
    driver: bridge

